version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: iex -S mix phx.server
    volumes:
      - .:/usr/local/phoenix
    links: [db]
    ports:
      - 4000:4000
      - 4004:4004
    stdin_open: true
    tty: true
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=we_reports
      - POSTGRES_PASSWORD=we_reports
      - POSTGRES_DB=we_reports_dev
    ports:
      - 5432:5432